### ISSUE TITLE
let <assignment> requires a semicolon or newline to terminate, while <assignment> doesn't

### ISSUE THREAD

**Issue by raff** [cloudcmds/tamarin#5]
I am playing with a REPL application where I read lines and run them through exec.Execute.

I found out that the following `let` statement throws an error when executing the line:

    > let a = 10
    Error: parse error: unterminated let statement

While the same assignment without `let` succeeds:

    > a = 20
    (*object.Integer) 20

I would have expected both statements to work the same (and actually everything else I tried does work without `;` or newline).

**Comment by myzie** [comment]
Thanks for the bug reports @raff! I think this one should be a quick fix. I'll probably be able to get to it shortly.

A REPL would definitely make sense. Thanks for giving the project a try.

**Comment by raff** [comment]
I'll open a PR when I have something I am happy with. There are a couple of small issues that I will report later, related to running multiple `Execute` with the same scope.

**Comment by myzie** [comment]
@raff - check out the linked PR. Open to suggestions on this.

**Comment by raff** [comment]
See my comment in the PR. Thanks!!!
