### ISSUE TITLE
backtick doesn't seem to work properly

### ISSUE THREAD

**Issue by raff** [cloudcmds/tamarin#6]
I am not sure if you are using the backtick for raw strings or for command execution, but it seems that parsing the closing backtick doesn't work properly.

This throws an error:

    > a = `ls -l`
    Error: parse error: no prefix parse function for ` found around line 1
    
This actually hangs the application:

   > a = `hello there
   signal: interrupt

**Comment by myzie** [comment]
We should use backticks for raw strings fwiw. Will look into this.

**Comment by myzie** [comment]
@raff - backticks should now work for raw strings, as of https://github.com/cloudcmds/tamarin/pull/9

Want to give it a try?

**Comment by raff** [comment]
The first issue is fixed. The 2nd is still hanging the app.

That would be something like this:
```
 line := "`hello there"
 result, err := exec.Execute(ctx, exec.Opts{Input: line})
```
I just run it through the debugger (delve) and got this:
```
> github.com/cloudcmds/tamarin/internal/lexer.(*Lexer).readChar() ./internal/lexer/lexer.go:60 (PC: 0x13f22d0)
    55:			l.linePosition = 0
    56:		} else {
    57:			l.linePosition++
    58:		}
    59:		// Set the current character and overall read position
=>  60:		if l.readPosition >= len(l.characters) {
    61:			l.ch = rune(0)
    62:		} else {
    63:			l.ch = l.characters[l.readPosition]
    64:		}
    65:		l.position = l.readPosition
```
The stacktrace is this:
```
0  0x00000000013f22d0 in github.com/cloudcmds/tamarin/internal/lexer.(*Lexer).readChar
    at ./internal/lexer/lexer.go:60
 1  0x00000000013f7005 in github.com/cloudcmds/tamarin/internal/lexer.(*Lexer).readBacktick
    at ./internal/lexer/lexer.go:458
 2  0x00000000013f54e7 in github.com/cloudcmds/tamarin/internal/lexer.(*Lexer).NextToken
    at ./internal/lexer/lexer.go:245
 3  0x00000000013fd512 in github.com/cloudcmds/tamarin/internal/parser.(*Parser).nextToken
    at ./internal/parser/parser.go:148
 4  0x0000000001407a79 in github.com/cloudcmds/tamarin/internal/parser.(*Parser).expectPeek
    at ./internal/parser/parser.go:1032
 5  0x00000000013fe933 in github.com/cloudcmds/tamarin/internal/parser.(*Parser).parseLetStatement
    at ./internal/parser/parser.go:229
 6  0x00000000013fe36e in github.com/cloudcmds/tamarin/internal/parser.(*Parser).parseStatement
    at ./internal/parser/parser.go:205
 7  0x00000000013fd756 in github.com/cloudcmds/tamarin/internal/parser.(*Parser).Parse
    at ./internal/parser/parser.go:155
 8  0x00000000013fbb8e in github.com/cloudcmds/tamarin/internal/parser.Parse
    at ./internal/parser/parser.go:29
 9  0x00000000016ad445 in github.com/cloudcmds/tamarin/exec.Execute
    at ./exec/exec.go:112
10  0x00000000016c1cee in main.main
    at ./cmd/repl/main.go:60
```

**Comment by raff** [comment]
And actually parsing a quoted string has the same problem. The issue is that readChar doesn't return an error (end of line or something) and readString/readBacktick only stop when getting the expected terminator (maybe you should check for terminator or \0)

**Comment by myzie** [comment]
Indeed! Thanks for the examples.

May be able to do a small fix again, but as you observed there are a couple areas where a larger scale change could be made to error handling. Will take another look at this.

**Comment by myzie** [comment]
Hi @raff, I merged some major error handling and error messaging updates. Could you give it a try?

**Comment by raff** [comment]
Looks good! Thanks!

**Comment by myzie** [comment]
Excellent, thanks for helping with this issue.

Fixed in https://github.com/cloudcmds/tamarin/releases/tag/v0.0.8
